- name: "{{ item.name }} download package"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ temp_dir }}"
  register: download

- name: "{{ item.name }} extract package"
  unarchive:
    remote_src: true
    src: "{{ download.dest }}"
    dest: "{{ temp_dir }}"
    list_files: true
  loop:
  when:
    - item.extract is defined and item.extract == True

- name: "Copy {{ item.name }} file to binary dir"
  copy:
    remote_src: true
    src: "{{ (temp_dir, (item.bin_path | default('')), (item.bin_name | default(item.name)) ) | path_join}}"
    dest: "{{ (local_bin_dir,  item.name ) | path_join }}"
    mode: 0755
#  when:
#    - item.bin_path is defined
#
#- name: "Copy {{ item.name }} file to binary dir"
#  copy:
#    remote_src: true
#    src: "{{ (temp_dir, (item.bin_name | default(item.name)) ) | path_join}}"
#    dest: "{{ (local_bin_dir, item.name ) | path_join }}"
#    mode: 0755
#  when:
#    - item.bin_path is undefined
