---
# tasks file for ansible-role-binaries
- name: Ensure {{ temp_dir }} is present
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Ensure {{ local_bin_dir }} is present
  file:
    path: "{{ local_bin_dir }}"
    state: directory

- name: Install {{ item.name }}
  include_tasks: install.yaml
  with_items: "{{ binaries }}"
